---
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "validator.fullname" . }}-database-config
  labels: {{- include "validator.labels" . | nindent 4 }}
data:
  {{- if .Values.postgresql.enabled }}
  POSTGRES_HOSTNAME: {{ .Release.Name }}-postgresql
  {{- else }}
  POSTGRES_HOSTNAME: {{ required "A valid .Values.postgresql.auth.hostname is required" .Values.postgresql.auth.hostname }}
  {{- end }}
  POSTGRES_PORT: {{ .Values.postgresql.auth.port | quote }}
  POSTGRES_USER: {{ required "A valid .Values.postgresql.auth.username is required" .Values.postgresql.auth.username }}
  POSTGRES_DB: {{ required "A valid .Values.postgresql.auth.database is required" .Values.postgresql.auth.database }}
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "validator.fullname" . }}-dapp
  labels: {{- include "validator.labels" . | nindent 4 }}
data:
  "dapp.json": |
    {
        "address": {{ required "A valid .Values.dapp.contractAddress is required" .Values.dapp.contractAddress | quote }},
        "blockHash": {{ required "A valid .Values.dapp.blockHash is required" .Values.dapp.blockHash | quote }},
        "blockNumber": {{ required "A valid .Values.dapp.blockNumber is required" .Values.dapp.blockNumber | int64 | quote }},
        "transactionHash": {{ required "A valid .Values.dapp.transactionHash is required" .Values.dapp.transactionHash | quote }}
    }
