{{- if eq .Values.postgresOperator.enabled false }}
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "validator.fullname" . }}-database-config
  labels: {{- include "validator.labels" . | nindent 4 }}
data:
  POSTGRES_HOSTNAME: {{ required "A valid .Values.dapp.postgres.hostname is required" .Values.dapp.postgres.hostname }}
  POSTGRES_PORT: {{ default "5432" .Values.dapp.postgres.port | quote }}
  POSTGRES_USER: {{ default "postgres" .Values.dapp.postgres.user }}
  POSTGRES_DB: {{ default "postgres" .Values.dapp.postgres.dbname }}
{{ end -}}
