---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "validator.fullname" . }}
  labels: {{- include "validator.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "validator.selectorLabels" . | nindent 6 }}
      rollups.cartesi.io/component: validator
  strategy:
    type: Recreate
  template:
    metadata:
      {{- with .Values.validator.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "validator.selectorLabels" . | nindent 8 }}
        rollups.cartesi.io/component: validator
    spec:
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "validator.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.validator.podSecurityContext | nindent 8 }}
      initContainers:
        {{- if .Values.validator.initContainers }}
        {{- include "tplvalues.render" ( dict "value" .Values.validator.initContainers "context" $ ) | nindent 8 }}
        {{- end }}
      containers:
        - name: rollups-dispatcher
          image: {{ include "dispatcher.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.validator.dispatcher.resources | nindent 12 }}
          args:
            {{- range .Values.validator.dispatcher.args }}
            - {{ . | quote}}
            {{- end }}
            {{- range .Values.validator.dispatcher.extraArgs }}
            - {{ . | quote}}
            {{- end }}
            initialDelaySeconds: 3
          env:
            - name: RUST_LOG
              value: {{ .Values.validator.dispatcher.logLevel }}
            {{- if .Values.validator.dispatcher.extraEnvVars }}
            {{- include "tplvalues.render" (dict "value" .Values.validator.dispatcher.extraEnvVars "context" $) | nindent 12 }}
            {{- end }}
          volumeMounts:
            - name: mnemonic
              mountPath: /var/run/secrets/mnemonic
              readOnly: true
            - name: dispatcher-lib
              mountPath: /opt/cartesi/rollups-dispatcher/lib
              readOnly: false
            {{- if .Values.validator.dispatcher.extraVolumeMounts }}
            {{- include "tplvalues.render" ( dict "value" .Values.validator.dispatcher.extraVolumeMounts "context" $ ) | nindent 12 }}
            {{- end }}

        - name: state-server
          image: {{ include "stateServer.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.validator.stateServer.resources | nindent 12 }}
          args:
            {{- range .Values.validator.stateServer.args }}
            - {{ . | quote}}
            {{- end }}
            {{- range .Values.validator.stateServer.extraArgs }}
            - {{ . | quote}}
            {{- end }}
          livenessProbe:
            exec:
              command:
                - grpc-health-probe
                - -addr=:50051
            initialDelaySeconds: 3
          env:
            - name: RUST_LOG
              value: {{ .Values.validator.stateServer.logLevel }}
            {{- if .Values.validator.stateServer.extraEnvVars }}
            {{- include "tplvalues.render" (dict "value" .Values.validator.stateServer.extraEnvVars "context" $) | nindent 12 }}
            {{- end }}
          ports:
            - containerPort: 50051
          volumeMounts:
            {{- if .Values.validator.stateServer.extraVolumeMounts }}
            {{- include "tplvalues.render" ( dict "value" .Values.validator.stateServer.extraVolumeMounts "context" $ ) | nindent 12 }}
            {{- end }}

        - name: rollups-indexer
          image: {{ include "indexer.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.validator.indexer.resources | nindent 12 }}
          args:
            {{- range .Values.validator.indexer.args }}
            - {{ . | quote}}
            {{- end }}
            {{- range .Values.validator.indexer.extraArgs }}
            - {{ . | quote}}
            {{- end }}
          env:
            - name: RUST_LOG
              value: {{ .Values.validator.indexer.logLevel }}
            {{- if .Values.validator.indexer.extraEnvVars }}
            {{- include "tplvalues.render" (dict "value" .Values.validator.indexer.extraEnvVars "context" $) | nindent 12 }}
            {{- end }}
            - name: POSTGRES_PASSWORD_FILE
              value: /var/run/secrets/postgres/PASSWORD
            - name: POSTGRES_MIGRATION_FOLDER
              value: /usr/local/bin/migrations/
          {{- if .Values.postgresOperator.enabled }}
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: secret-{{ include "validator.fullname" . }}-indexer
                  key: ROLE
                  optional: false
            - name: POSTGRES_HOSTNAME
              valueFrom:
                secretKeyRef:
                  name: secret-{{ include "validator.fullname" . }}-indexer
                  key: HOST
                  optional: false
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: secret-{{ include "validator.fullname" . }}-indexer
                  key: DATABASE_NAME
                  optional: false
            - name: POSTGRES_PORT
              value: "5432"
          {{- else }}
          envFrom:
            - configMapRef:
                name: {{ include "validator.fullname" . }}-database-config
          {{- end }}
          volumeMounts:
            - name: postgres
              mountPath: /var/run/secrets/postgres
              readOnly: true
            {{- if .Values.validator.indexer.extraVolumeMounts }}
            {{- include "tplvalues.render" ( dict "value" .Values.validator.indexer.extraVolumeMounts "context" $ ) | nindent 12 }}
            {{- end }}

      volumes:
        - name: dispatcher-lib
          emptyDir: {}
        - name: mnemonic
          secret:
            {{- if .Values.dapp.mnemonic.value }}
            secretName: {{ include "validator.fullname" . }}-mnemonic
            {{- else }}
            secretName: {{ .Values.dapp.mnemonic.secretRef }}
            {{- end }}
        - name: postgres
          secret:
          {{- if .Values.postgresOperator.enabled }}
            secretName: secret-{{ include "validator.fullname" . }}-indexer
            items:
              - key: PASSWORD
                path: PASSWORD
          {{- else }}
            secretName: {{ include "validator.fullname" . }}-postgres
          {{- end }}
        {{- if .Values.validator.extraVolumes }}
        {{- include "tplvalues.render" ( dict "value" .Values.validator.extraVolumes "context" $ ) | nindent 8 }}
        {{- end }}
      {{- with .Values.validator.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.validator.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.validator.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "validator.fullname" . }}-server-manager
  labels: {{- include "validator.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "validator.selectorLabels" . | nindent 6 }}
      rollups.cartesi.io/component: server-manager
  strategy:
    type: Recreate
  template:
    metadata:
      {{- with .Values.validator.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "validator.selectorLabels" . | nindent 8 }}
        rollups.cartesi.io/component: server-manager
    spec:
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "validator.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.serverManager.podSecurityContext | nindent 8 }}
      initContainers:
        {{- if .Values.serverManager.initContainers }}
        {{- include "tplvalues.render" ( dict "value" .Values.serverManager.initContainers "context" $ ) | nindent 8 }}
        {{- end }}
      containers:
        - name: broker-proxy
          image: {{ include "serverManager.brokerProxy.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.serverManager.brokerProxy.resources | nindent 12 }}
          args:
            {{- range .Values.serverManager.brokerProxy.args }}
            - {{ . | quote}}
            {{- end }}
            {{- range .Values.serverManager.brokerProxy.extraArgs }}
            - {{ . | quote}}
            {{- end }}
          env:
            - name: RUST_LOG
              value: {{ .Values.serverManager.brokerProxy.logLevel }}
            {{- if .Values.serverManager.brokerProxy.extraEnvVars }}
            {{- include "tplvalues.render" (dict "value" .Values.serverManager.brokerProxy.extraEnvVars "context" $) | nindent 12 }}
            {{- end }}
          volumeMounts:
            {{- if .Values.serverManager.brokerProxy.extraVolumeMounts }}
            {{- include "tplvalues.render" ( dict "value" .Values.serverManager.brokerProxy.extraVolumeMounts "context" $ ) | nindent 12 }}
            {{- end }}

        - name: server-manager
          image: {{ required "A valid .Values.dapp.image is required" .Values.dapp.image }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.serverManager.resources | nindent 12 }}
          livenessProbe:
            exec:
              command:
                - grpc-health-probe
                - -addr=:5001
            initialDelaySeconds: 5
            periodSeconds: 5
          args:
            {{- range .Values.serverManager.args }}
            - {{ . | quote}}
            {{- end }}
            {{- range .Values.serverManager.extraArgs }}
            - {{ . | quote}}
            {{- end }}
          ports:
            - containerPort: 5001
          env:
            - name: SERVER_MANAGER_LOG_LEVEL
              value: {{ .Values.serverManager.logLevel }}
            - name: REMOTE_CARTESI_MACHINE_LOG_LEVEL
              value: {{ coalesce .Values.serverManager.remoteCartesiMachine.logLevel .Values.serverManager.logLevel }}
            {{- if .Values.serverManager.extraEnvVars }}
            {{- include "tplvalues.render" (dict "value" .Values.serverManager.extraEnvVars "context" $) | nindent 12 }}
            {{- end }}
          volumeMounts:
            {{- if .Values.serverManager.extraVolumeMounts }}
            {{- include "tplvalues.render" ( dict "value" .Values.serverManager.extraVolumeMounts "context" $ ) | nindent 12 }}
            {{- end }}

      volumes:
        {{- if .Values.serverManager.extraVolumes }}
        {{- include "tplvalues.render" ( dict "value" .Values.serverManager.extraVolumes "context" $ ) | nindent 8 }}
        {{- end }}
      {{- with .Values.serverManager.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.serverManager.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.serverManager.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "validator.fullname" . }}-endpoints
  labels: {{- include "validator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.endpoints.replicaCount }}
  selector:
    matchLabels:
      {{- include "validator.selectorLabels" . | nindent 6 }}
      rollups.cartesi.io/component: endpoints
  template:
    metadata:
      labels:
        {{- include "validator.selectorLabels" . | nindent 8 }}
        rollups.cartesi.io/component: endpoints
    spec:
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "validator.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.endpoints.podSecurityContext | nindent 8 }}
      initContainers:
        {{- if .Values.endpoints.initContainers }}
        {{- include "tplvalues.render" ( dict "value" .Values.endpoints.initContainers "context" $ ) | nindent 8 }}
        {{- end }}
      containers:
        - name: rollups-inspect-server
          image: {{ include "inspectServer.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.endpoints.inspectServer.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: 5005
            initialDelaySeconds: 3
          args:
            {{- range .Values.endpoints.inspectServer.args }}
            - {{ . | quote}}
            {{- end }}
            {{- range .Values.endpoints.inspectServer.extraArgs }}
            - {{ . | quote}}
            {{- end }}
          env:
            - name: RUST_LOG
              value: {{ .Values.endpoints.inspectServer.logLevel }}
            {{- if .Values.endpoints.inspectServer.extraEnvVars }}
            {{- include "tplvalues.render" (dict "value" .Values.endpoints.inspectServer.extraEnvVars "context" $) | nindent 12 }}
            {{- end }}
          volumeMounts:
            {{- if .Values.endpoints.inspectServer.extraVolumeMounts }}
            {{- include "tplvalues.render" ( dict "value" .Values.endpoints.inspectServer.extraVolumeMounts "context" $ ) | nindent 12 }}
            {{- end }}
          ports:
            - containerPort: 5005

        - name: query-server
          image: {{ include "queryServer.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.endpoints.queryServer.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: 4000
            initialDelaySeconds: 3
          env:
            - name: RUST_LOG
              value: {{ .Values.endpoints.queryServer.logLevel }}
            {{- if .Values.endpoints.queryServer.extraEnvVars }}
            {{- include "tplvalues.render" (dict "value" .Values.endpoints.queryServer.extraEnvVars "context" $) | nindent 12 }}
            {{- end }}
            - name: GRAPHQL_HOST
              value: "0.0.0.0"
            - name: GRAPHQL_PORT
              value: "4000"
            - name: POSTGRES_PASSWORD_FILE
              value: /var/run/secrets/postgres/PASSWORD
          {{- if .Values.postgresOperator.enabled }}
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: secret-{{ include "validator.fullname" . }}-query-server
                  key: ROLE
                  optional: false
            - name: POSTGRES_HOSTNAME
              valueFrom:
                secretKeyRef:
                  name: secret-{{ include "validator.fullname" . }}-query-server
                  key: HOST
                  optional: false
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: secret-{{ include "validator.fullname" . }}-query-server
                  key: DATABASE_NAME
                  optional: false
          {{- else }}
          envFrom:
            - configMapRef:
                name: {{ include "validator.fullname" . }}-database-config
          {{- end }}
          volumeMounts:
            - name: postgres
              mountPath: /var/run/secrets/postgres
              readOnly: true
            {{- if .Values.endpoints.inspectServer.extraVolumeMounts }}
            {{- include "tplvalues.render" ( dict "value" .Values.endpoints.inspectServer.extraVolumeMounts "context" $ ) | nindent 12 }}
            {{- end }}
          ports:
            - containerPort: 4000
      {{- with .Values.endpoints.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.endpoints.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.endpoints.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      volumes:
        - name: postgres
        {{- if .Values.postgresOperator.enabled }}
          secret:
            secretName: secret-{{ include "validator.fullname" . }}-query-server
            items:
              - key: PASSWORD
                path: PASSWORD
        {{- else }}
          secret:
            secretName: {{ include "validator.fullname" . }}-postgres
        {{- end }}
        {{- if .Values.endpoints.extraVolumes }}
        {{- include "tplvalues.render" ( dict "value" .Values.endpoints.extraVolumes "context" $ ) | nindent 8 }}
        {{- end }}
