{{- if .Values.postgresql.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "validator.fullname" . }}-postgres
  labels: {{- include "validator.labels" . | nindent 4 }}
type: Opaque
data:
  PASSWORD: {{ required "A valid .Values.postgresql.auth.password sholud is required" .Values.postgresql.auth.password | b64enc | quote }}
{{- end }}
