---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "validator.fullname" . }}-query-server
  labels: {{- include "validator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.queryServer.service.type }}
  ports:
    - port: {{ .Values.queryServer.service.port }}
      targetPort: 4000
      protocol: TCP
      name: graphql
  selector:
    {{- include "validator.selectorLabels" . | nindent 4 }}
    app: {{ include "validator.fullname" . }}-query-server
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "validator.fullname" . }}-inspect-server
  labels: {{- include "validator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.machineManager.inspectServer.service.type }}
  ports:
    - port: {{ .Values.machineManager.inspectServer.service.port }}
      targetPort: 5005
      protocol: TCP
      name: inspect-server
  selector:
    {{- include "validator.selectorLabels" . | nindent 4 }}
    app: {{ include "validator.fullname" . }}-machine-manager
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "validator.fullname" . }}-server-manager
  labels: {{- include "validator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.machineManager.serverManager.service.type }}
  ports:
    - port: {{ .Values.machineManager.serverManager.service.port }}
      targetPort: 5001
      protocol: TCP
      name: server-manager
  selector:
    {{- include "validator.selectorLabels" . | nindent 4 }}
    app: {{ include "validator.fullname" . }}-machine-manager
