name: Lint and Test Charts

on: pull_request

jobs:
  lint-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure test-values
        env:
          MNEMONIC: ${{ secrets.MNEMONIC }}
          ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY }}
          TEST_VALUES_PATH: ./charts/rollups-validator-node/ci/test-values.yaml
        run: cat $TEST_VALUES_PATH.tpl | envsubst > $TEST_VALUES_PATH

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.8.1

      - uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.2.1
        with:
          version: v3.6.0

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --target-branch ${{ github.event.repository.default_branch }})
          if [[ -n "$changed" ]]; then
            echo "::set-output name=changed::true"
          fi

      - name: Run chart-testing (lint)
        run: ct lint --target-branch ${{ github.event.repository.default_branch }}

      - name: Create kind cluster
        uses: helm/kind-action@v1.3.0
        if: steps.list-changed.outputs.changed == 'true'

      - name: Install postgres service to kind cluster
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm install postgresql bitnami/postgresql \
            --namespace default \
            --wait \
            --set auth.postgresPassword=postgres

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Create regcred Kubernetes Secret
        run: |
          kubectl create secret generic --namespace=default regcred \
            --from-file=.dockerconfigjson=$HOME/.docker/config.json \
            --type=kubernetes.io/dockerconfigjson

      - name: Run chart-testing (install)
        run: |
          ct install \
            --debug \
            --namespace default \
            --target-branch ${{ github.event.repository.default_branch }}
